# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Multinode Simple Low SLO Configuration - Best effort service
# Uses disaggregated prefill-decode architecture with planner auto-scaling
Common:
  model: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  block-size: 128
  max-model-len: 4096
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  router: kv-load

Frontend:
  served_model_name: deepseek-ai/DeepSeek-R1-Distill-Llama-8B-low-slo
  endpoint: low_slo_multinode.Processor.chat/completions
  port: 8002
  router: round-robin
  common-configs: [block-size]

Processor:
  common-configs: [model, block-size, router]

Router:
  min-workers: 1
  common-configs: [model, block-size, router]

# Decode workers - planner will auto-launch minimum required workers
VllmWorker:
  remote-prefill: true
  conditional-disagg: false  # Always use remote prefill for consistent performance
  max-num-batched-tokens: 8192
  enable-prefix-caching: false
  max-num-seqs: 128
  gpu-memory-utilization: 0.9  # Higher memory usage for low SLO
  ServiceArgs:
    workers: 0  # Planner will auto-launch minimum required workers
    resources:
      gpu: '1'   # 1 GPU per decode worker
  common-configs: [model, block-size, max-model-len, kv-transfer-config]

# Prefill workers - planner will auto-launch minimum required workers
PrefillWorker:
  max-num-batched-tokens: 16384  # Higher batch size for prefill
  gpu-memory-utilization: 0.9  # Higher memory usage for low SLO
  ServiceArgs:
    workers: 0  # Planner will auto-launch minimum required workers
    resources:
      gpu: '1'   # 1 GPU per prefill worker
  common-configs: [model, block-size, max-model-len, kv-transfer-config]

# Planner for automatic scaling
Planner:
  environment: local
  no-operation: false
  metric-pulling-interval: 1
  adjustment-interval: 10
  prefill-queue-scale-down-threshold: 0.1
  prefill-queue-scale-up-threshold: 0.2   # Scale up prefill when queue size > 0.3
  decode-kv-scale-down-threshold: 0.1
  decode-kv-scale-up-threshold: 0.2     # Scale up decode when KV utilization > 30%
  log-dir: logs/planner_low_slo_multinode 