# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# PD Disaggregated High SLO Configuration - Optimized for <1s response time
# Uses GPUs 0-3, starts with 2 GPUs (1P+1D), can scale to 4 GPUs
# GPU allocation: High SLO pool uses physical GPUs 0-3
Common:
  model: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  block-size: 64
  max-model-len: 4096
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  router: kv-load
  gpu-scope: "0,1,2,3"  # GPU scope for this pool

Frontend:
  served_model_name: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  endpoint: dynamo.Processor.chat/completions
  port: 8000
  router: round-robin
  common-configs: [block-size]
  ServiceArgs:
    dynamo:
      namespace: high_slo_pd

Processor:
  common-configs: [model, block-size, router]
  ServiceArgs:
    dynamo:
      namespace: high_slo_pd

Router:
  min-workers: 1
  common-configs: [model, block-size, router]
  ServiceArgs:
    dynamo:
      namespace: high_slo_pd

# Decode workers - planner will auto-launch minimum required workers
VllmWorker:
  remote-prefill: true
  conditional-disagg: false  # Always use remote prefill for consistent performance
  max-num-batched-tokens: 4096
  enable-prefix-caching: true
  max-num-seqs: 32
  gpu-memory-utilization: 0.85  # Reduce memory usage
  ServiceArgs:
    workers: 0  # Planner will auto-launch minimum required workers
    resources:
      gpu: '1'   # 1 GPU per decode worker (planner assigns within range)
    dynamo:
      namespace: high_slo_pd
  common-configs: [model, block-size, max-model-len, kv-transfer-config]

# Prefill workers - planner will auto-launch minimum required workers
PrefillWorker:
  max-num-batched-tokens: 8192  # Higher batch size for prefill
  gpu-memory-utilization: 0.85  # Reduce memory usage
  ServiceArgs:
    workers: 0  # Planner will auto-launch minimum required workers
    resources:
      gpu: '1'   # 1 GPU per prefill worker (planner assigns within range)
    dynamo:
      namespace: high_slo_pd
  common-configs: [model, block-size, max-model-len, kv-transfer-config]

# Planner for automatic scaling
Planner:
  environment: local
  no-operation: false
  metric-pulling-interval: 1
  adjustment-interval: 10
  prefill-queue-scale-down-threshold: 0.1
  prefill-queue-scale-up-threshold: 0.2   # Scale up prefill when queue size > 0.2
  decode-kv-scale-down-threshold: 0.1
  decode-kv-scale-up-threshold: 0.2     # Scale up decode when KV utilization > 20%
  log-dir: logs/planner_high_slo
  ServiceArgs:
    dynamo:
      namespace: high_slo_pd 