# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# PD Disaggregated Low SLO Configuration - Optimized for throughput
# Uses GPUs 4-7, starts with 2 GPUs (1P+1D), can scale to 4 GPUs
# GPU allocation: Low SLO pool uses physical GPUs 4-7
Common:
  model: Qwen/Qwen2.5-3B-Instruct
  block-size: 64
  max-model-len: 8192
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  router: kv-load
  gpu-scope: "4-7"  # GPU scope for this pool

Frontend:
  served_model_name: Qwen/Qwen2.5-3B-Instruct
  endpoint: dynamo.Processor.chat/completions
  port: 8002
  router: round-robin
  common-configs: [block-size]
  ServiceArgs:
    dynamo:
      namespace: low_slo_pd

Processor:
  common-configs: [model, block-size, router]
  ServiceArgs:
    dynamo:
      namespace: low_slo_pd

Router:
  min-workers: 1
  common-configs: [model, block-size, router]
  ServiceArgs:
    dynamo:
      namespace: low_slo_pd

# Decode workers - start with 1, can scale via planner
VllmWorker:
  remote-prefill: true
  conditional-disagg: false  # Always use remote prefill for consistent performance
  max-num-batched-tokens: 8192  # Higher batch size for throughput
  enable-prefix-caching: true
  max-num-seqs: 64
  gpu-memory-utilization: 0.85  # Reduce memory usage
  ServiceArgs:
    workers: 1  # Start with 1 decode worker
    resources:
      gpu: '1'   # 1 GPU per decode worker (planner assigns within range)
    dynamo:
      namespace: low_slo_pd
  common-configs: [model, block-size, max-model-len, kv-transfer-config]

# Prefill workers - start with 1, can scale via planner
PrefillWorker:
  max-num-batched-tokens: 16384  # Higher batch size for prefill throughput
  gpu-memory-utilization: 0.85  # Reduce memory usage
  ServiceArgs:
    workers: 1  # Start with 1 prefill worker
    resources:
      gpu: '1'   # 1 GPU per prefill worker (planner assigns within range)
    dynamo:
      namespace: low_slo_pd
  common-configs: [model, block-size, max-model-len, kv-transfer-config]

# Planner for automatic scaling
Planner:
  environment: local
  no-operation: false
  metric-pulling-interval: 1
  adjustment-interval: 10
  prefill-queue-scale-down-threshold: 0.2
  prefill-queue-scale-up-threshold: 6   # Scale up prefill when queue size > 6 (lower than high SLO)
  decode-kv-scale-down-threshold: 0.4
  decode-kv-scale-up-threshold: 0.8     # Scale up decode when KV utilization > 80% (higher than high SLO)
  log-dir: logs/planner_low_slo
  ServiceArgs:
    dynamo:
      namespace: low_slo_pd 